  apiVersion: v1alpha1
  kind: AgentConfig
  rendezvousIP: 192.168.111.100
  hosts:
    - hostname: master0
      role: master
      interfaces:
        - name: enp0s4
          macAddress: 00:21:50:90:c0:10
        - name: enp0s5
          macAddress: 00:21:50:90:c0:20
      networkConfig:
        interfaces:
          - name: bond0
            type: bond
            state: up
            mac-address: 00:21:50:90:c0:10
            ipv4:
              enabled: true
              address:
                - ip: 192.168.111.100
                  prefix-length: 24
            ipv6:
              enabled: false
            link-aggregation:
              mode: active-backup
              options:
                miimon: "150"
              port:
                - enp0s4
                - enp0s5
        dns-resolver:
          config:
            server:
              - 10.10.10.11
              - 10.10.10.12
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.111.1
              next-hop-interface: bond0
              table-id: 254
